---
title: "Margin of Error"
output: html_notebook
---

```{r}
library(tidycensus)
library(censusapi)
library(dplyr)
library(tidyverse)
```

```{r}
#NC plumbing data and unit occupancy data via the Census
Sys.setenv(CENSUS_KEY="f8926d2beb514da70fdcd1abdac3eab3c261b34a")
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_KEY")

vars2010 <- load_variables(2010, "acs5", cache = TRUE)
#View(vars2010)

plumbing2018 <- get_acs(geography = "county",
                        variables = "B25048_003E", 
                        state = "NC",
                        year = 2018)
plumbing2018 <- plumbing2018 %>%
  select(-variable)

plumbing2009 <- get_acs(geography = "county",
                        variables = "B25048_003E",
                        state = "NC",
                        year = 2009)
plumbing2009 <- plumbing2009 %>%
  select(-variable)
```

```{r}
#Cleaning the column names
names(plumbing2018)[names(plumbing2018) == "NAME"] <- "County"
names(plumbing2018)[names(plumbing2018) == "estimate"] <- "IncompletePlumbing2018"
names(plumbing2018)[names(plumbing2018) == "moe"] <- "MarginofError"

names(plumbing2009)[names(plumbing2009) == "NAME"] <- "County"
names(plumbing2009)[names(plumbing2009) == "estimate"] <- "IncompletePlumbing2009"
names(plumbing2009)[names(plumbing2009) == "moe"] <- "MarginofError"
```

```{r}
#Margin of error work

moedata <- merge(plumbing2009, plumbing2018, by = "GEOID")

names(moedata)[names(moedata) == "MarginofError.x"] <- "MarginofError2009"
names(moedata)[names(moedata) == "MarginofError.y"] <- "MarginofError2018"

moedata <- moedata %>%
  select(-County.y)

moedata <- moedata %>%
  mutate(
    min2009 = IncompletePlumbing2009 - MarginofError2009,
    max2018 = IncompletePlumbing2018 + MarginofError2018
  ) %>%
  mutate(
    diff = min2009 - max2018
  )
```
